// ============================================================
// OPPORTUNITY SOURCE REGISTRY
// Vetted directory of official opportunity sources, feeds, and programs.
// Stores official domain, collection method, trust level, and categories.
// ============================================================
import type { SourceDefinition } from "./types";

export const SOURCE_REGISTRY: SourceDefinition[] = [
  // --- 1. Open Source & Technical Fellowships ---
  {
    id: "gsoc",
    name: "Google Summer of Code",
    type: "curated",
    official_domain: "summerofcode.withgoogle.com",
    category: "internship",
    default_mode: "remote",
    is_verified_source: true,
    refresh_interval_days: 7,
    description: "Global stipend program bringing new contributors into open source software development.",
    tags: ["Open Source", "Global", "Stipend", "Students", "Software"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["internship", "other"],
    last_successful_check: "2026-03-01T00:00:00Z",
  },
  {
    id: "mlh-fellowship",
    name: "MLH Fellowship",
    type: "curated",
    official_domain: "fellowship.mlh.io",
    category: "fellowship",
    default_mode: "remote",
    is_verified_source: true,
    refresh_interval_days: 7,
    description: "12-week remote software engineering internship alternative working on production open-source software.",
    tags: ["Open Source", "Stipend", "Remote", "Software Engineering"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["fellowship", "internship"],
    last_successful_check: "2026-03-05T00:00:00Z",
  },
  {
    id: "outreachy",
    name: "Outreachy Diversity Internships",
    type: "curated",
    official_domain: "outreachy.org",
    category: "internship",
    default_mode: "remote",
    is_verified_source: true,
    refresh_interval_days: 14,
    description: "$7,000 paid remote internships for people subject to systemic bias and underrepresented in tech.",
    tags: ["Diversity", "Open Source", "Remote", "Stipend"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["internship"],
    last_successful_check: "2026-03-02T00:00:00Z",
  },
  {
    id: "lfx-mentorship",
    name: "Linux Foundation LFX Mentorship",
    type: "curated",
    official_domain: "lfx.linuxfoundation.org",
    category: "internship",
    default_mode: "remote",
    is_verified_source: true,
    refresh_interval_days: 14,
    description: "Paid open source mentorship with Linux Foundation projects including Kubernetes, Hyperledger, and Envoy.",
    tags: ["Linux", "Cloud", "Stipend", "Open Source", "Remote"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["internship"],
    last_successful_check: "2026-03-01T00:00:00Z",
  },

  // --- 2. Research Fellowships & Internships ---
  {
    id: "mitacs-globalink",
    name: "Mitacs Globalink Research Internship",
    type: "curated",
    official_domain: "mitacs.ca",
    category: "internship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 14,
    description: "Competitive 12-week funded research internship at Canadian universities for international undergrads.",
    tags: ["Research", "Canada", "Fully Funded", "Undergraduates", "Academic"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["internship", "fellowship"],
    last_successful_check: "2026-02-28T00:00:00Z",
  },
  {
    id: "cern-summer-student",
    name: "CERN Summer Student Programme",
    type: "curated",
    official_domain: "careers.cern",
    category: "internship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 14,
    description: "8-13 weeks at CERN Geneva for physics, computing, and engineering students with generous daily allowance.",
    tags: ["Physics", "Computing", "Switzerland", "Stipend", "Prestigious"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["internship", "fellowship"],
    last_successful_check: "2026-03-04T00:00:00Z",
  },
  {
    id: "caltech-surf",
    name: "Caltech SURF (Summer Undergraduate Research Fellowship)",
    type: "curated",
    official_domain: "sfp.caltech.edu",
    category: "fellowship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 30,
    description: "10-week summer research with Caltech faculty, NASA JPL scientists, and $7,740 stipend.",
    tags: ["Research", "Space", "Caltech", "USA", "Undergraduates"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["fellowship", "internship"],
    last_successful_check: "2026-02-20T00:00:00Z",
  },
  {
    id: "oxford-ml-research",
    name: "Oxford ML Research Group Fellowship",
    type: "curated",
    official_domain: "ox.ac.uk",
    category: "fellowship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 30,
    description: "6-month paid placement at the Department of Engineering Science exploring deep probabilistic ML.",
    tags: ["Machine Learning", "Oxford", "UK", "Research", "Stipend"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["fellowship"],
    last_successful_check: "2026-02-15T00:00:00Z",
  },
  {
    id: "stanford-ai4all",
    name: "Stanford AI4ALL Research Fellowship",
    type: "curated",
    official_domain: "ai4all.org",
    category: "fellowship",
    default_mode: "remote",
    is_verified_source: true,
    refresh_interval_days: 14,
    description: "Research cohort introducing undergraduates to human-centered artificial intelligence applications.",
    tags: ["AI", "Research", "Diversity", "Students"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["fellowship"],
    last_successful_check: "2026-03-02T00:00:00Z",
  },
  {
    id: "weizmann-kupcinet",
    name: "Weizmann Institute Kupcinet-Getz International Summer Science",
    type: "curated",
    official_domain: "weizmann.ac.il",
    category: "internship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 30,
    description: "Fully funded 8-week research fellowship in Israel in math, physics, chemistry, and life sciences.",
    tags: ["Science", "Research", "Fully Funded", "Global"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["internship", "fellowship"],
    last_successful_check: "2026-02-10T00:00:00Z",
  },

  // --- 3. Founder, Fellowship & Startup Programs ---
  {
    id: "thiel-fellowship",
    name: "The Thiel Fellowship",
    type: "curated",
    official_domain: "thielfellowship.org",
    category: "fellowship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 30,
    description: "Two-year, $100,000 grant for young founders who want to build new things instead of sitting in college.",
    tags: ["Startup", "Grant", "Founders", "High Upside", "Global"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["fellowship", "grant"],
    last_successful_check: "2026-03-01T00:00:00Z",
  },
  {
    id: "yc-summer",
    name: "Y Combinator Summer Batch",
    type: "curated",
    official_domain: "ycombinator.com",
    category: "fellowship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 14,
    description: "Early-stage startup funding ($500k standard deal) and 3-month acceleration in San Francisco.",
    tags: ["Startups", "Investment", "Prestige", "Founders", "SF"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["fellowship", "other"],
    last_successful_check: "2026-03-06T00:00:00Z",
  },
  {
    id: "neo-scholars",
    name: "Neo Scholars & Fellows",
    type: "curated",
    official_domain: "neo.com",
    category: "fellowship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 30,
    description: "Community of top 1% computer science students and veteran tech leaders, with guaranteed funding and mentorship.",
    tags: ["Community", "Prestige", "CS", "Mentorship", "USA"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["fellowship"],
    last_successful_check: "2026-03-01T00:00:00Z",
  },
  {
    id: "kleiner-perkins-fellows",
    name: "Kleiner Perkins Fellows Program",
    type: "curated",
    official_domain: "fellows.kleinerperkins.com",
    category: "fellowship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 30,
    description: "Pairs outstanding engineering, design, and product students with top Silicon Valley startups for a summer.",
    tags: ["Silicon Valley", "Engineering", "Design", "Product", "Venture"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["fellowship", "internship"],
    last_successful_check: "2026-02-25T00:00:00Z",
  },
  {
    id: "emergent-ventures",
    name: "Emergent Ventures Grant (Mercatus Center)",
    type: "curated",
    official_domain: "mercatus.org",
    category: "grant",
    default_mode: "remote",
    is_verified_source: true,
    refresh_interval_days: 14,
    description: "Fast, unbureaucratic grants ($5,000 to $100,000) for moonshot ideas, scalable projects, and exceptional talent.",
    tags: ["Grants", "Tyler Cowen", "Moonshots", "Global", "No Bureaucracy"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["grant", "fellowship"],
    last_successful_check: "2026-03-08T00:00:00Z",
  },
  {
    id: "80000-hours",
    name: "80,000 Hours High-Impact Project Grants",
    type: "curated",
    official_domain: "80000hours.org",
    category: "grant",
    default_mode: "remote",
    is_verified_source: true,
    refresh_interval_days: 30,
    description: "Funding for students and young builders working on pressing global problems like AI safety, biorisk, and policy.",
    tags: ["Effective Altruism", "AI Safety", "Biorisk", "Funding"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["grant"],
    last_successful_check: "2026-03-03T00:00:00Z",
  },

  // --- 4. Flagship Hackathons & Competitions ---
  {
    id: "hackmit",
    name: "HackMIT 2026",
    type: "curated",
    official_domain: "hackmit.org",
    category: "hackathon",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 7,
    description: "Flagship annual hackathon organized by MIT students with international travel grants.",
    tags: ["Hackathon", "Travel Grants", "Undergraduates", "Prizes"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["hackathon"],
    last_successful_check: "2026-03-07T00:00:00Z",
  },
  {
    id: "calhacks",
    name: "Cal Hacks 12.0",
    type: "curated",
    official_domain: "calhacks.io",
    category: "hackathon",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 7,
    description: "The world's largest collegiate hackathon hosted at UC Berkeley and San Francisco.",
    tags: ["Hackathon", "Berkeley", "SF", "AI", "Hardware"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["hackathon"],
    last_successful_check: "2026-03-05T00:00:00Z",
  },
  {
    id: "ethglobal",
    name: "ETHGlobal Hackathon Series",
    type: "curated",
    official_domain: "ethglobal.com",
    category: "hackathon",
    default_mode: "hybrid",
    is_verified_source: true,
    refresh_interval_days: 7,
    description: "Premier Web3 and decentralized systems hackathon series with $500k+ prize pools in cities globally and online.",
    tags: ["Web3", "Ethereum", "Crypto", "Prizes", "Global"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["hackathon"],
    last_successful_check: "2026-03-09T00:00:00Z",
  },
  {
    id: "hackharvard",
    name: "HackHarvard 2026",
    type: "curated",
    official_domain: "hackharvard.io",
    category: "hackathon",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 14,
    description: "36-hour collegiate hackathon held on Harvard University campus in Cambridge, MA.",
    tags: ["Harvard", "Hackathon", "Prizes", "Students"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["hackathon"],
    last_successful_check: "2026-02-28T00:00:00Z",
  },
  {
    id: "pennapps",
    name: "PennApps XXVI",
    type: "curated",
    official_domain: "pennapps.com",
    category: "hackathon",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 14,
    description: "The original student-run college hackathon founded in 2009 at the University of Pennsylvania.",
    tags: ["Penn", "Hackathon", "Legacy", "Prizes"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["hackathon"],
    last_successful_check: "2026-02-25T00:00:00Z",
  },

  // --- 5. Scholarships & Academic Grants ---
  {
    id: "rhodes-trust",
    name: "The Rhodes Scholarship (Oxford)",
    type: "curated",
    official_domain: "rhodeshouse.ox.ac.uk",
    category: "scholarship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 30,
    description: "Fully funded postgraduate award enabling exceptional young people from around the world to study at Oxford.",
    tags: ["Scholarship", "Oxford", "Fully Funded", "Global", "Postgraduate"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["scholarship"],
    last_successful_check: "2026-02-15T00:00:00Z",
  },
  {
    id: "schwarzman-scholars",
    name: "Schwarzman Scholars (Tsinghua)",
    type: "curated",
    official_domain: "schwarzmanscholars.org",
    category: "scholarship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 30,
    description: "One-year master's degree at Tsinghua University in Beijing with full funding, travel, and stipend.",
    tags: ["Global Affairs", "Beijing", "China", "Full Scholarship", "Leadership"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["scholarship"],
    last_successful_check: "2026-02-20T00:00:00Z",
  },
  {
    id: "knight-hennessy",
    name: "Knight-Hennessy Scholars (Stanford)",
    type: "curated",
    official_domain: "knight-hennessy.stanford.edu",
    category: "scholarship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 30,
    description: "Full funding for graduate degrees at Stanford University across engineering, law, medicine, and business.",
    tags: ["Stanford", "Full Funding", "Leadership", "Global"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["scholarship"],
    last_successful_check: "2026-02-22T00:00:00Z",
  },
  {
    id: "generation-google-emea",
    name: "Generation Google Scholarship (EMEA & APAC)",
    type: "curated",
    official_domain: "buildyourfuture.withgoogle.com",
    category: "scholarship",
    default_mode: "remote",
    is_verified_source: true,
    refresh_interval_days: 14,
    description: "€7,000 / $2,500 scholarship for computer science students who demonstrate passion for tech and leadership.",
    tags: ["Google", "Scholarship", "Diversity", "Computer Science"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["scholarship"],
    last_successful_check: "2026-03-01T00:00:00Z",
  },
  {
    id: "palantir-pathways",
    name: "Palantir Women in Tech & Future Leaders Scholarship",
    type: "curated",
    official_domain: "palantir.com",
    category: "scholarship",
    default_mode: "remote",
    is_verified_source: true,
    refresh_interval_days: 30,
    description: "$7,000 scholarship and guaranteed invitation to interview for technical internships.",
    tags: ["Palantir", "Scholarship", "Women in Tech", "Internship Fast-Track"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["scholarship", "internship"],
    last_successful_check: "2026-02-18T00:00:00Z",
  },

  // --- 6. Industry Tech Internships & Accelerator Programs ---
  {
    id: "jane-street-in-focus",
    name: "Jane Street IN FOCUS & Fellowship",
    type: "curated",
    official_domain: "janestreet.com",
    category: "fellowship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 14,
    description: "Immersion programs and software/quantitative research internships in NYC, London, and Hong Kong.",
    tags: ["Finance", "Quantitative", "OCaml", "Top Stipend", "NYC", "London"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["fellowship", "internship"],
    last_successful_check: "2026-03-06T00:00:00Z",
  },
  {
    id: "meta-university",
    name: "Meta University (Engineering & Analytics)",
    type: "curated",
    official_domain: "metacareers.com",
    category: "internship",
    default_mode: "in-person",
    is_verified_source: true,
    refresh_interval_days: 14,
    description: "10-week paid summer internship program for 1st and 2nd year students from historically underrepresented backgrounds.",
    tags: ["Meta", "Early Career", "Undergrads", "Paid", "Software"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["internship"],
    last_successful_check: "2026-02-28T00:00:00Z",
  },
  {
    id: "uber-she++",
    name: "Uber STAR Internship Program",
    type: "curated",
    official_domain: "uber.com",
    category: "internship",
    country: "US",
    default_mode: "in-person",
    is_verified_source: true,
    is_enabled: true,
    refresh_interval_days: 30,
    description: "12-week summer technical internship for 2nd-year engineering students with direct engineering mentorship.",
    tags: ["Uber", "Software", "Internship", "Paid", "Underrepresented"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["internship"],
    last_successful_check: "2026-02-20T00:00:00Z",
  },

  // --- 7. Multi-Country Research, Grants, Hackathons & Accelerators ---
  {
    id: "tcs-research-scholars",
    name: "TCS Research Scholar Program",
    type: "curated",
    official_domain: "tcs.com",
    category: "research_programme",
    country: "India",
    default_mode: "in-person",
    is_verified_source: true,
    is_enabled: true,
    refresh_interval_days: 30,
    description: "Prestige research fellowship for full-time PhD scholars in computer science and AI across premier Indian institutes.",
    tags: ["India", "Research", "Fellowship", "PhD", "AI", "Funded"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["research_programme", "fellowship"],
    last_successful_check: "2026-03-01T00:00:00Z",
  },
  {
    id: "smart-india-hackathon",
    name: "Smart India Hackathon (SIH)",
    type: "official_feed",
    official_domain: "sih.gov.in",
    category: "hackathon",
    country: "India",
    default_mode: "in-person",
    is_verified_source: true,
    is_enabled: true,
    refresh_interval_days: 14,
    description: "World's largest nationwide open innovation model for university students to solve national challenges.",
    tags: ["India", "Hackathon", "Prize", "Government", "Innovation"],
    collection_method: "feed",
    trust_level: "official",
    supported_categories: ["hackathon", "competition"],
    last_successful_check: "2026-03-05T00:00:00Z",
  },
  {
    id: "turing-scheme-uk",
    name: "UK Turing Scheme Global Placements",
    type: "curated",
    official_domain: "turing-scheme.org.uk",
    category: "international_programme",
    country: "United Kingdom",
    default_mode: "in-person",
    is_verified_source: true,
    is_enabled: true,
    refresh_interval_days: 30,
    description: "UK government scheme funding global study and work abroad placements for higher education students.",
    tags: ["UK", "International", "Study Abroad", "Funded", "Global"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["international_programme", "grant"],
    last_successful_check: "2026-03-02T00:00:00Z",
  },
  {
    id: "epfl-summer-research",
    name: "EPFL Summer Research Program in Computer Science",
    type: "curated",
    official_domain: "epfl.ch",
    category: "research_programme",
    country: "Switzerland",
    default_mode: "in-person",
    is_verified_source: true,
    is_enabled: true,
    refresh_interval_days: 14,
    description: "Paid 3-month summer research fellowships at EPFL labs in Switzerland for international undergrad and masters students.",
    tags: ["Switzerland", "Europe", "Research", "Stipend", "AI", "Systems"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["research_programme", "fellowship", "international_programme"],
    last_successful_check: "2026-03-04T00:00:00Z",
  },
  {
    id: "github-campus-experts",
    name: "GitHub Campus Experts Program",
    type: "curated",
    official_domain: "githubcampus.expert",
    category: "open_source_programme",
    country: "GLOBAL",
    default_mode: "remote",
    is_verified_source: true,
    is_enabled: true,
    refresh_interval_days: 14,
    description: "Global student leadership program providing training, resources, and event funding to build tech communities.",
    tags: ["GitHub", "Open Source", "Global", "Community", "Leadership"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["open_source_programme", "grant"],
    last_successful_check: "2026-03-07T00:00:00Z",
  },
  {
    id: "techstars-accelerator",
    name: "Techstars Accelerator Programs",
    type: "curated",
    official_domain: "techstars.com",
    category: "accelerator",
    country: "US",
    default_mode: "hybrid",
    is_verified_source: true,
    is_enabled: true,
    refresh_interval_days: 14,
    description: "3-month accelerator providing $120k funding, worldwide network, and hands-on mentorship for early-stage founders.",
    tags: ["Startup", "Accelerator", "Seed Funding", "Mentorship", "Global"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["accelerator", "startup_programme"],
    last_successful_check: "2026-03-06T00:00:00Z",
  },
  {
    id: "iclr-travel-grants",
    name: "ICLR / NeurIPS Student Travel Grants",
    type: "curated",
    official_domain: "iclr.cc",
    category: "conference",
    country: "GLOBAL",
    default_mode: "in-person",
    is_verified_source: true,
    is_enabled: true,
    refresh_interval_days: 14,
    description: "Financial support covering registration, flights, and accommodation for student researchers presenting at top AI conferences.",
    tags: ["AI", "Machine Learning", "Conference", "Travel Grant", "Research"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["conference", "grant"],
    last_successful_check: "2026-03-03T00:00:00Z",
  },
  {
    id: "imagine-cup",
    name: "Microsoft Imagine Cup Global Student Competition",
    type: "curated",
    official_domain: "imaginecup.microsoft.com",
    category: "competition",
    country: "GLOBAL",
    default_mode: "hybrid",
    is_verified_source: true,
    is_enabled: true,
    refresh_interval_days: 14,
    description: "Global student tech competition with $100,000 grand prize, Microsoft mentorship, and Azure cloud grants.",
    tags: ["Competition", "Prize", "Microsoft", "AI", "Startups", "Global"],
    collection_method: "curated",
    trust_level: "official",
    supported_categories: ["competition", "grant"],
    last_successful_check: "2026-03-05T00:00:00Z",
  }
];

export function getAllSources(): SourceDefinition[] {
  return SOURCE_REGISTRY.map((s) => ({
    ...s,
    country: s.country || "GLOBAL",
    is_enabled: s.is_enabled ?? true,
    last_status: s.last_status || "healthy",
    error_count: s.error_count || 0,
  }));
}

export function getSourcesByCountry(country: string): SourceDefinition[] {
  const norm = country.toLowerCase();
  return getAllSources().filter(
    (s) => (s.country || "").toLowerCase() === norm || s.country === "GLOBAL"
  );
}

export function getSourcesByCategory(category: string): SourceDefinition[] {
  const norm = category.toLowerCase();
  return getAllSources().filter(
    (s) => s.category.toLowerCase() === norm || s.supported_categories?.some((c) => c.toLowerCase() === norm)
  );
}

export function updateSourceStatus(
  sourceId: string,
  updates: Partial<SourceDefinition>
): boolean {
  const source = SOURCE_REGISTRY.find((s) => s.id === sourceId);
  if (!source) return false;
  Object.assign(source, updates);
  return true;
}

