// ============================================================
// CONTEXT EXPORT — generates Markdown and JSON context packs
// No server processing. User controls what is included.
// Private contact data and sensitive fields excluded by default.
// ============================================================
import { Profile, ProfileEvidence, Opportunity, ApplicationAnswer } from "@/types/database";
import { APP_NAME, APP_DISPLAY_NAME, APP_INTERNAL_NAME } from "@/config/app";

interface ExportSections {
  background: boolean;
  education: boolean;
  skills: boolean;
  evidence: boolean;
  preferences: boolean;
}

export function generateContextMarkdown(
  profile: Profile,
  evidence: ProfileEvidence[],
  sections: ExportSections
): string {
  const lines: string[] = [];
  const now = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

  lines.push(`# Personal Context Pack`);
  lines.push(`> Generated by ${APP_NAME} on ${now}. This export contains only the sections you selected.`);
  lines.push("");
  lines.push("---");
  lines.push("");

  if (sections.background) {
    lines.push("## Background");
    if (profile.display_name) lines.push(`- **Name:** ${profile.display_name}`);
    if (profile.country_of_residence) lines.push(`- **Country of residence:** ${profile.country_of_residence}`);
    if (profile.nationalities?.length) lines.push(`- **Nationalities:** ${profile.nationalities.join(", ")}`);
    lines.push("");
  }

  if (sections.education) {
    lines.push("## Education");
    if (profile.university) lines.push(`- **University:** ${profile.university}`);
    if (profile.degree) lines.push(`- **Degree:** ${profile.degree}`);
    if (profile.field_of_study) lines.push(`- **Field:** ${profile.field_of_study}`);
    if (profile.education_stage) lines.push(`- **Stage:** ${profile.education_stage}`);
    if (profile.expected_graduation) lines.push(`- **Expected graduation:** ${profile.expected_graduation}`);
    lines.push("");
  }

  if (sections.skills) {
    lines.push("## Skills & Interests");
    if (profile.skills?.length) lines.push(`- **Skills:** ${profile.skills.join(", ")}`);
    if (profile.interests?.length) lines.push(`- **Interests:** ${profile.interests.join(", ")}`);
    lines.push("");
  }

  if (sections.preferences) {
    lines.push("## Opportunity Preferences");
    if (profile.opportunity_types?.length) lines.push(`- **Looking for:** ${profile.opportunity_types.join(", ")}`);
    if (profile.participation_preference) lines.push(`- **Participation mode:** ${profile.participation_preference}`);
    if (profile.travel_constraints) lines.push(`- **Travel constraints:** ${profile.travel_constraints}`);
    lines.push("");
  }

  if (sections.evidence && evidence.length > 0) {
    lines.push("## Projects & Evidence");
    for (const ev of evidence) {
      lines.push(`### ${ev.title}`);
      lines.push(`- **Kind:** ${ev.kind}`);
      if (ev.start_date || ev.end_date) {
        const end = ev.end_date ?? "present";
        lines.push(`- **Period:** ${ev.start_date ?? "—"} to ${end}`);
      }
      if (ev.description) lines.push(`- **Description:** ${ev.description}`);
      if (ev.tags?.length) lines.push(`- **Tags:** ${ev.tags.join(", ")}`);
      if (ev.evidence_url) lines.push(`- **Link:** ${ev.evidence_url}`);
      lines.push("");
    }
  }

  return lines.join("\n");
}

export function generateContextJson(
  profile: Profile,
  evidence: ProfileEvidence[],
  sections: ExportSections
): string {
  const now = new Date().toISOString();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const output: Record<string, any> = {
    _meta: {
      generated_by: `${APP_DISPLAY_NAME} (${APP_INTERNAL_NAME})`,
      generated_at: now,
      note: "This export contains only user-selected sections. Contact data and sensitive fields are excluded.",
    },
  };

  if (sections.background) {
    output.background = {
      display_name: profile.display_name,
      country_of_residence: profile.country_of_residence,
      nationalities: profile.nationalities,
    };
  }

  if (sections.education) {
    output.education = {
      university: profile.university,
      degree: profile.degree,
      field_of_study: profile.field_of_study,
      education_stage: profile.education_stage,
      expected_graduation: profile.expected_graduation,
    };
  }

  if (sections.skills) {
    output.skills_and_interests = {
      skills: profile.skills,
      interests: profile.interests,
    };
  }

  if (sections.preferences) {
    output.preferences = {
      opportunity_types: profile.opportunity_types,
      participation_preference: profile.participation_preference,
      travel_constraints: profile.travel_constraints,
    };
  }

  if (sections.evidence) {
    output.evidence = evidence.map((ev) => ({
      kind: ev.kind,
      title: ev.title,
      description: ev.description,
      start_date: ev.start_date,
      end_date: ev.end_date,
      tags: ev.tags,
      evidence_url: ev.evidence_url,
      confirmed: ev.confirmed,
    }));
  }

  return JSON.stringify(output, null, 2);
}

// ============================================================
// OPPORTUNITY-SPECIFIC CONTEXT — export for a single opportunity
// ============================================================

interface OpportunityExportOptions {
  includeOpportunityDetails: boolean;
  includeRequirements: boolean;
  includeProfile: boolean;
  includeEvidence: boolean;
  includeAnswers: boolean;
  includeEligibility: boolean;
  format: "markdown" | "json";
}

export function generateOpportunityContext(
  opportunity: Opportunity,
  profile: Profile,
  evidence: ProfileEvidence[],
  answers: ApplicationAnswer[],
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  eligibilityReport: Record<string, any> | null,
  options: OpportunityExportOptions
): string {
  if (options.format === "json") {
    return generateOpportunityContextJson(opportunity, profile, evidence, answers, eligibilityReport, options);
  }
  return generateOpportunityContextMarkdown(opportunity, profile, evidence, answers, eligibilityReport, options);
}

function generateOpportunityContextMarkdown(
  opportunity: Opportunity,
  profile: Profile,
  evidence: ProfileEvidence[],
  answers: ApplicationAnswer[],
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  eligibilityReport: Record<string, any> | null,
  options: OpportunityExportOptions
): string {
  const lines: string[] = [];
  const now = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

  lines.push(`# Application Context: ${opportunity.title}`);
  lines.push(`> Generated by ${APP_NAME} on ${now}`);
  lines.push("");

  if (options.includeOpportunityDetails) {
    lines.push("## Opportunity");
    lines.push(`- **Title:** ${opportunity.title}`);
    if (opportunity.organizer) lines.push(`- **Organizer:** ${opportunity.organizer}`);
    if (opportunity.category) lines.push(`- **Category:** ${opportunity.category}`);
    if (opportunity.deadline) lines.push(`- **Deadline:** ${opportunity.deadline}`);
    if (opportunity.location) lines.push(`- **Location:** ${opportunity.location}`);
    if (opportunity.participation_mode) lines.push(`- **Mode:** ${opportunity.participation_mode}`);
    if (opportunity.funding_kind) lines.push(`- **Funding:** ${opportunity.funding_kind}`);
    if (opportunity.funding_description) lines.push(`- **Funding details:** ${opportunity.funding_description}`);
    if (opportunity.summary) lines.push(`\n### Summary\n${opportunity.summary}`);
    lines.push("");
  }

  if (options.includeRequirements && opportunity.requirements) {
    const reqs = opportunity.requirements as Record<string, unknown>;
    const items = Array.isArray(reqs.items) ? (reqs.items as Array<{ text: string; type: string; mandatory: string }>) : [];
    if (items.length > 0) {
      lines.push("## Requirements");
      for (const r of items) {
        lines.push(`- [${r.mandatory}] ${r.text}`);
      }
      lines.push("");
    }
    const appQuestions = Array.isArray(reqs.application_questions) ? (reqs.application_questions as string[]) : [];
    if (appQuestions.length > 0) {
      lines.push("## Application Questions");
      for (const q of appQuestions) {
        lines.push(`- ${q}`);
      }
      lines.push("");
    }
    const docs = Array.isArray(reqs.required_documents) ? (reqs.required_documents as string[]) : [];
    if (docs.length > 0) {
      lines.push("## Required Documents");
      for (const d of docs) {
        lines.push(`- [ ] ${d}`);
      }
      lines.push("");
    }
  }

  if (options.includeProfile) {
    lines.push("## Your Profile (relevant excerpts)");
    if (profile.display_name) lines.push(`- **Name:** ${profile.display_name}`);
    if (profile.nationalities?.length) lines.push(`- **Nationalities:** ${profile.nationalities.join(", ")}`);
    if (profile.education_stage) lines.push(`- **Education:** ${profile.education_stage}`);
    if (profile.field_of_study) lines.push(`- **Field:** ${profile.field_of_study}`);
    if (profile.skills?.length) lines.push(`- **Skills:** ${profile.skills.join(", ")}`);
    lines.push("");
  }

  if (options.includeEvidence && evidence.length > 0) {
    lines.push("## Relevant Experience");
    for (const ev of evidence) {
      lines.push(`- **${ev.title}** (${ev.kind}): ${ev.description ?? "No description"}`);
      if (ev.tags?.length) lines.push(`  Tags: ${ev.tags.join(", ")}`);
    }
    lines.push("");
  }

  if (options.includeAnswers && answers.length > 0) {
    lines.push("## Application Answers");
    for (const ans of answers) {
      lines.push(`### Q: ${ans.question}`);
      lines.push(ans.answer_draft ?? "(no draft yet)");
      lines.push("");
    }
  }

  if (options.includeEligibility && eligibilityReport) {
    lines.push("## Eligibility Report");
    lines.push(`- **Verdict:** ${eligibilityReport.overall_verdict ?? "unknown"}`);
    lines.push(`- **Readiness:** ${eligibilityReport.readiness_score ?? 0}%`);
    if (eligibilityReport.blockers?.length > 0) {
      lines.push(`- **Blockers:** ${eligibilityReport.blockers.join("; ")}`);
    }
    if (eligibilityReport.gaps?.length > 0) {
      lines.push(`- **Gaps:** ${eligibilityReport.gaps.join("; ")}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function generateOpportunityContextJson(
  opportunity: Opportunity,
  profile: Profile,
  evidence: ProfileEvidence[],
  answers: ApplicationAnswer[],
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  eligibilityReport: Record<string, any> | null,
  options: OpportunityExportOptions
): string {
  const output: Record<string, unknown> = {
    _meta: {
      generated_by: `${APP_DISPLAY_NAME} (${APP_INTERNAL_NAME})`,
      generated_at: new Date().toISOString(),
      opportunity_id: opportunity.id,
    },
  };

  if (options.includeOpportunityDetails) {
    output.opportunity = {
      title: opportunity.title,
      organizer: opportunity.organizer,
      category: opportunity.category,
      deadline: opportunity.deadline,
      location: opportunity.location,
      participation_mode: opportunity.participation_mode,
      funding_kind: opportunity.funding_kind,
      funding_description: opportunity.funding_description,
      summary: opportunity.summary,
    };
  }

  if (options.includeRequirements && opportunity.requirements) {
    const reqs = opportunity.requirements as Record<string, unknown>;
    output.requirements = {
      items: Array.isArray(reqs.items) ? reqs.items : [],
      application_questions: Array.isArray(reqs.application_questions) ? reqs.application_questions : [],
      required_documents: Array.isArray(reqs.required_documents) ? reqs.required_documents : [],
      application_steps: Array.isArray(reqs.application_steps) ? reqs.application_steps : [],
    };
  }

  if (options.includeProfile) {
    output.profile = {
      display_name: profile.display_name,
      nationalities: profile.nationalities,
      education_stage: profile.education_stage,
      field_of_study: profile.field_of_study,
      skills: profile.skills,
    };
  }

  if (options.includeEvidence) {
    output.evidence = evidence.map((ev) => ({
      title: ev.title,
      kind: ev.kind,
      description: ev.description,
      tags: ev.tags,
    }));
  }

  if (options.includeAnswers) {
    output.answers = answers.map((a) => ({
      question: a.question,
      answer_draft: a.answer_draft,
    }));
  }

  if (options.includeEligibility && eligibilityReport) {
    output.eligibility = eligibilityReport;
  }

  return JSON.stringify(output, null, 2);
}
