'use client';
import { useState } from 'react';
import Link from 'next/link';
import { AdminGuard } from '@/components/auth/AdminGuard';
interface Candidate { title: string; source_url: string; edition_year: number | null; excerpt: string }
export default function AdminImportPage() {
  const [markdown, setMarkdown] = useState(''), [repository, setRepository] = useState(''), [candidates, setCandidates] = useState<Candidate[]>([]), [selected, setSelected] = useState<Set<string>>(new Set()), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  async function request(body: Record<string, unknown>) { const response = await fetch('/api/admin/import', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Import failed'); return data; }
  const input = () => repository.trim() ? { repository: repository.trim() } : { markdown };
  async function preview() { setBusy(true); setMessage(''); try { const data = await request(input()); setCandidates(data.candidates); setSelected(new Set(data.candidates.map((item: Candidate) => item.source_url))); setMessage(`${data.candidates.length} linked listings found. Confirm each title and provider link before saving.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Preview failed'); } finally { setBusy(false); } }
  async function save() { setBusy(true); setMessage(''); try { const data = await request({ ...input(), action: 'save', urls: [...selected] }); setMessage(`${data.saved} saved as private drafts; ${data.duplicates} matching URL and edition already existed. Review drafts and verify official sources before publishing.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Import failed'); } finally { setBusy(false); } }
  return <AdminGuard><main className="page-frame max-w-4xl space-y-5"><Link className="text-sm underline" href="/admin">← Admin</Link><h1 className="page-title">Import opportunity lists</h1><p>Import a public GitHub repository README or paste Markdown links. This imports titles and links into private drafts. It does not crawl the repository or mark programme details verified.</p><label className="block space-y-2"><span>Public GitHub repository</span><input className="input" value={repository} onChange={event => { setRepository(event.target.value); if (event.target.value) setMarkdown(''); }} placeholder="https://github.com/owner/repository" /></label><p className="text-center text-sm">or paste Markdown</p><textarea className="input min-h-64" maxLength={250000} value={markdown} onChange={event => { setMarkdown(event.target.value); if (event.target.value) setRepository(''); }} placeholder={'- [Research Fellowship 2027](https://provider.example/program)'} /><div className="flex gap-3"><button disabled={busy || (!markdown.trim() && !repository.trim())} className="btn btn-secondary" onClick={preview}>Preview links</button>{candidates.length > 0 && <button disabled={busy || !selected.size} className="btn btn-primary" onClick={save}>Save selected drafts</button>}</div>{message && <p role="status" className="alert">{message}</p>}<section className="space-y-3">{candidates.map(candidate => <label key={candidate.source_url} className="card p-4 flex gap-3 items-start"><input type="checkbox" checked={selected.has(candidate.source_url)} onChange={event => setSelected(previous => { const next = new Set(previous); if (event.target.checked) next.add(candidate.source_url); else next.delete(candidate.source_url); return next; })}/><span className="min-w-0"><strong className="block">{candidate.title}{candidate.edition_year ? ` · ${candidate.edition_year}` : ''}</strong><a className="text-sm break-all underline" href={candidate.source_url} target="_blank" rel="noreferrer">{candidate.source_url}</a><span className="block text-xs text-gray-500 mt-1">Source details still need review. No eligibility or funding claims have been inferred.</span></span></label>)}</section></main></AdminGuard>;
}
