// ============================================================
// DEMO MODE DATA — used when Supabase credentials are absent.
// All records are clearly fictional. Never used in production.
// ============================================================
import { Opportunity, Profile, Application, ApplicationTask, ApplicationAnswer, ProfileEvidence, ImportedOpportunity } from "@/types/database";

export const DEMO_USER_ID = "demo-user-00000000-0000-0000-0000-000000000001";

export const DEMO_PROFILE: Profile = {
  id: DEMO_USER_ID,
  display_name: "Demo Student",
  country_of_residence: "GB",
  nationalities: ["GB"],
  university: "University of Notional Studies (fictional)",
  degree: "BSc Computer Science",
  field_of_study: "Computer Science",
  education_stage: "undergraduate",
  expected_graduation: "2026-06-01",
  skills: ["Python", "React", "Machine Learning"],
  interests: ["Climate Tech", "EdTech", "Open Source"],
  opportunity_types: ["hackathon", "fellowship", "internship"],
  participation_preference: "remote",
  travel_constraints: null,
  max_budget_amount: null,
  max_budget_currency: null,
  age_band: null,
  is_admin: true,
  onboarding_completed: true,
  updated_at: new Date().toISOString(),
};

export const DEMO_OPPORTUNITIES: Opportunity[] = [
  {
    id: "demo-opp-00000000-0000-0000-0000-000000000001",
    created_by: null,
    title: "[DEMO] Aurora Fellowship 2025",
    organizer: "Northern Lights Foundation (fictional)",
    category: "fellowship",
    summary:
      "A fictional 10-week fellowship for undergraduates interested in climate policy. This is demo data — not a real listing.",
    source_url: "https://example.com/aurora-fellowship",
    location: "Helsinki, Finland",
    participation_mode: "in-person",
    funding_description:
      "Stipend: €2,000/month. Travel and accommodation covered. No participation cost.",
    funding_kind: "stipend",
    deadline: new Date(Date.now() + 45 * 86400000).toISOString(),
    timezone_known: true,
    source_content: null,
    retrieved_at: new Date().toISOString(),
    source_status: "live",
    requirements: null,
    status: "published",
    is_demo: true,
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-opp-00000000-0000-0000-0000-000000000002",
    created_by: null,
    title: "[DEMO] Global Hackathon 2025",
    organizer: "OpenTech Initiative (fictional)",
    category: "hackathon",
    summary:
      "A fictional 48-hour virtual hackathon for teams of 2–5 building open-source tools. This is demo data — not a real listing.",
    source_url: "https://example.com/global-hackathon",
    location: "Fully Remote",
    participation_mode: "remote",
    funding_description:
      "Prize pool: $50,000 total (1st place $20,000, 2nd $10,000, 3rd $5,000). No entry fee.",
    funding_kind: "prize",
    deadline: new Date(Date.now() + 22 * 86400000).toISOString(),
    timezone_known: true,
    source_content: null,
    retrieved_at: new Date().toISOString(),
    source_status: "live",
    requirements: null,
    status: "published",
    is_demo: true,
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-opp-00000000-0000-0000-0000-000000000003",
    created_by: null,
    title: "[DEMO] Emerging Scholars Scholarship",
    organizer: "University Trust Fund (fictional)",
    category: "scholarship",
    summary:
      "A fictional needs-based scholarship for first-generation university students. This is demo data — not a real listing.",
    source_url: "https://example.com/emerging-scholars",
    location: "United Kingdom",
    participation_mode: "in-person",
    funding_description:
      "Award: £5,000 per academic year. No travel required for application.",
    funding_kind: "stipend",
    deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
    timezone_known: true,
    source_content: null,
    retrieved_at: new Date().toISOString(),
    source_status: "live",
    requirements: null,
    status: "published",
    is_demo: true,
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-opp-00000000-0000-0000-0000-000000000004",
    created_by: null,
    title: "[DEMO] Startup Internship — Product Track",
    organizer: "Fictional Ventures Ltd. (fictional)",
    category: "internship",
    summary:
      "A fictional 12-week paid internship for students interested in product management at early-stage startups. This is demo data — not a real listing.",
    source_url: "https://example.com/startup-internship",
    location: "San Francisco, CA, USA or Remote",
    participation_mode: "hybrid",
    funding_description:
      "Stipend: $6,000/month. Fully remote option available.",
    funding_kind: "stipend",
    deadline: new Date(Date.now() + 30 * 86400000).toISOString(),
    timezone_known: true,
    source_content: null,
    retrieved_at: new Date().toISOString(),
    source_status: "live",
    requirements: null,
    status: "published",
    is_demo: true,
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-opp-00000000-0000-0000-0000-000000000005",
    created_by: null,
    title: "[DEMO] Community Innovation Grant",
    organizer: "Local Futures Foundation (fictional)",
    category: "grant",
    summary:
      "A fictional grant for student-led community projects. Maximum award $2,500. This is demo data — not a real listing.",
    source_url: "https://example.com/community-grant",
    location: "United States",
    participation_mode: "in-person",
    funding_description:
      "Grant: up to $2,500. No participation cost. Recipients must provide a brief report at project conclusion.",
    funding_kind: "prize",
    deadline: new Date(Date.now() - 5 * 86400000).toISOString(),
    timezone_known: true,
    source_content: null,
    retrieved_at: new Date().toISOString(),
    source_status: "closed",
    requirements: null,
    status: "published",
    is_demo: true,
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_APPLICATIONS: Application[] = [
  {
    id: "demo-app-00000000-0000-0000-0000-000000000001",
    user_id: DEMO_USER_ID,
    opportunity_id: "demo-opp-00000000-0000-0000-0000-000000000002",
    stage: "preparing",
    next_action: "Write project proposal",
    target_date: new Date(Date.now() + 15 * 86400000).toISOString().split("T")[0],
    notes: "Team of 3. Focus on ML for climate data.",
    submitted_at: null,
    sort_order: 200,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-app-00000000-0000-0000-0000-000000000002",
    user_id: DEMO_USER_ID,
    opportunity_id: "demo-opp-00000000-0000-0000-0000-000000000001",
    stage: "saved",
    next_action: "Review eligibility requirements",
    target_date: null,
    notes: null,
    submitted_at: null,
    sort_order: 100,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_TASKS: ApplicationTask[] = [
  {
    id: "demo-task-00000000-0000-0000-0000-000000000001",
    application_id: "demo-app-00000000-0000-0000-0000-000000000001",
    user_id: DEMO_USER_ID,
    title: "Register team on hackathon portal",
    completed: true,
    due_date: null,
    sort_order: 100,
    pinned_to_today: true,
    source_required: true,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-task-00000000-0000-0000-0000-000000000002",
    application_id: "demo-app-00000000-0000-0000-0000-000000000001",
    user_id: DEMO_USER_ID,
    title: "Write project proposal",
    completed: false,
    due_date: new Date(Date.now() + 10 * 86400000).toISOString().split("T")[0],
    sort_order: 200,
    pinned_to_today: true,
    source_required: true,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-task-00000000-0000-0000-0000-000000000003",
    application_id: "demo-app-00000000-0000-0000-0000-000000000001",
    user_id: DEMO_USER_ID,
    title: "Prepare GitHub repository",
    completed: false,
    due_date: new Date(Date.now() + 18 * 86400000).toISOString().split("T")[0],
    sort_order: 300,
    pinned_to_today: false,
    source_required: false,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_ANSWERS: ApplicationAnswer[] = [
  {
    id: "demo-ans-00000000-0000-0000-0000-000000000001",
    application_id: "demo-app-00000000-0000-0000-0000-000000000001",
    user_id: DEMO_USER_ID,
    question: "Describe your project idea in 200 words.",
    answer_draft: "We plan to build an open-source tool that uses machine learning to visualize local climate data for community decision-making...",
    evidence_ids: [],
    revised_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const DEMO_EVIDENCE: ProfileEvidence[] = [
  {
    id: "demo-ev-00000000-0000-0000-0000-000000000001",
    user_id: DEMO_USER_ID,
    kind: "project",
    title: "ClimateViz — open-source climate data explorer",
    description:
      "Built a React + Python tool to visualize NOAA datasets. Used by 200+ students at local university.",
    start_date: "2024-09-01",
    end_date: null,
    tags: ["Python", "React", "Data Visualization", "Climate"],
    evidence_url: "https://github.com/example/climateviz",
    confirmed: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-ev-00000000-0000-0000-0000-000000000002",
    user_id: DEMO_USER_ID,
    kind: "achievement",
    title: "1st place — Regional Sustainability Hackathon",
    description:
      "Led a team of 4 to build a carbon footprint tracker. Awarded £500 prize.",
    start_date: "2024-03-15",
    end_date: "2024-03-17",
    tags: ["Hackathon", "Leadership", "Sustainability"],
    evidence_url: null,
    confirmed: true,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ============================================================
// CURATED REAL OPPORTUNITIES — genuine listings for demo mode
// Current 2026 editions with live deadlines.
// Historical editions are clearly marked as closed.
// ============================================================
export const DEMO_REAL_OPPORTUNITIES: ImportedOpportunity[] = [
  {
    id: "c1000000-0000-4000-8000-000000000001",
    created_by: "system",
    title: "Google Summer of Code 2026",
    organizer: "Google Open Source",
    category: "internship",
    summary:
      "A global program bringing new contributors into open source. Students work with an open source organization on a 3+ month programming project and receive a stipend upon successful completion.",
    location: "Remote",
    participation_mode: "remote",
    deadline: "2026-11-15T23:59:59Z",
    deadline_timezone: "UTC",
    deadline_timezone_known: true,
    deadline_raw_text: "November 15, 2026",
    funding_kind: "stipend",
    funding_description: "Stipend paid in phases based on project milestones. Amount varies by country.",
    funding_amount_min: 1500,
    funding_amount_max: 6000,
    funding_currency: "USD",
    funding_conditional: false,
    requirements: [
      { text: "Must be 18 years or older", type: "age", mandatory: "mandatory", excerpt: "You must be 18 years or older", source_ref: "eligibility", comparison_rule: { field: "age", operator: "gte", value: 18 }, uncertainty: null },
      { text: "Must be enrolled in or accepted to a post-secondary institution", type: "education_stage", mandatory: "mandatory", excerpt: "Must be enrolled in or accepted to a post-secondary academic program", source_ref: "eligibility", comparison_rule: { field: "education_stage", operator: "in_list", value: ["undergraduate", "masters", "phd"] }, uncertainty: null },
      { text: "Must be a confirmed student as of GSoC acceptance", type: "education_stage", mandatory: "mandatory", excerpt: "You must be a student as of the GSoC acceptance announcement", source_ref: "eligibility", comparison_rule: null, uncertainty: "Requires student status confirmation" },
      { text: "Must be able to work 175+ hours over 3 months", type: "experience", mandatory: "mandatory", excerpt: "You should be prepared to work at least 175 hours on your project", source_ref: "timeline", comparison_rule: null, uncertainty: null },
      { text: "Must have previous experience with version control (Git)", type: "skill", mandatory: "preferred", excerpt: "Familiarity with Git and open source workflows", source_ref: "requirements", comparison_rule: { field: "skill", operator: "includes", value: "git" }, uncertainty: null },
    ],
    application_questions: [
      "Describe your interest in open source and this organization",
      "What relevant programming experience do you have?",
      "Why are you interested in this particular project?",
    ],
    required_documents: ["CV/Resume"],
    application_steps: [
      "Find an organization and project idea",
      "Contact the organization mentors",
      "Submit proposal via GSoC portal",
      "Wait for acceptance decision",
    ],
    source_url: "https://summerofcode.withgoogle.com/",
    source_content: "Google Summer of Code is a global program focused on bringing more developers into open source software development. Students work with an open source organization on a 3+ month programming project. Participants receive a stipend upon successful completion.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000002",
    created_by: "system",
    title: "Mitacs Globalink Research Internship 2026",
    organizer: "Mitacs",
    category: "internship",
    summary:
      "A 12-week research internship for undergraduate students at Canadian universities. Work with a Canadian professor on a research project. Fully funded including airfare and stipend.",
    location: "Canada",
    participation_mode: "in-person",
    deadline: "2026-09-22T23:59:59Z",
    deadline_timezone: "UTC",
    deadline_timezone_known: true,
    deadline_raw_text: "September 22, 2026",
    funding_kind: "stipend",
    funding_description: "Round-trip airfare, stipend, and insurance covered by Mitacs.",
    funding_amount_min: 3000,
    funding_amount_max: 8000,
    funding_currency: "CAD",
    funding_conditional: false,
    requirements: [
      { text: "Must be enrolled in an undergraduate program", type: "education_stage", mandatory: "mandatory", excerpt: "Currently enrolled in a degree-granting program at an eligible university", source_ref: "eligibility", comparison_rule: { field: "education_stage", operator: "equals", value: "undergraduate" }, uncertainty: null },
      { text: "Must be at least 18 years of age", type: "age", mandatory: "mandatory", excerpt: "At least 18 years of age", source_ref: "eligibility", comparison_rule: { field: "age", operator: "gte", value: 18 }, uncertainty: null },
      { text: "Must have completed at least 2 years of university", type: "education_stage", mandatory: "mandatory", excerpt: "Must have completed at least 2 full years of study", source_ref: "eligibility", comparison_rule: null, uncertainty: "Requires verification of completed years" },
      { text: "Must have a valid passport", type: "document", mandatory: "mandatory", excerpt: "A valid passport is required for travel", source_ref: "documents", comparison_rule: { field: "document", operator: "equals", value: "valid passport" }, uncertainty: null },
    ],
    application_questions: [
      "Why are you interested in this research internship?",
      "Describe your research experience and interests",
      "How does this internship align with your career goals?",
    ],
    required_documents: ["CV/Resume", "Transcript", "Two reference letters"],
    application_steps: [
      "Browse available projects",
      "Submit application through Mitacs portal",
      "Interview with professor",
      "Acceptance and travel arrangements",
    ],
    source_url: "https://www.mitacs.ca/en/programs/globalink-research-internship",
    source_content: "Mitacs Globalink Research Internship offers 12-week research internships for undergraduate students at Canadian universities. The program covers round-trip airfare, stipend, and health insurance.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000003",
    created_by: "system",
    title: "HackMIT 2026",
    organizer: "MIT student volunteers",
    category: "hackathon",
    summary:
      "One of the largest student-run hackathons in the US. 24 hours of building, learning, and innovating. Open to all college students worldwide.",
    location: "Cambridge, MA (hybrid)",
    participation_mode: "hybrid",
    deadline: "2026-09-14T23:59:59Z",
    deadline_timezone: "America/New_York",
    deadline_timezone_known: true,
    deadline_raw_text: "September 14, 2026",
    funding_kind: "reimbursement",
    funding_description: "Travel reimbursement available. Meals and snacks provided at venue.",
    funding_amount_min: 100,
    funding_amount_max: 500,
    funding_currency: "USD",
    funding_conditional: true,
    requirements: [
      { text: "Must be a college/university student", type: "education_stage", mandatory: "mandatory", excerpt: "Open to all college students", source_ref: "eligibility", comparison_rule: { field: "education_stage", operator: "in_list", value: ["undergraduate", "masters", "phd"] }, uncertainty: null },
      { text: "Must be 18 or older", type: "age", mandatory: "mandatory", excerpt: "Must be 18 or older", source_ref: "eligibility", comparison_rule: { field: "age", operator: "gte", value: 18 }, uncertainty: null },
      { text: "Teams of 1-4 people", type: "team_size", mandatory: "mandatory", excerpt: "Teams of 1 to 4", source_ref: "rules", comparison_rule: { field: "team_size", operator: "lte", value: 4 }, uncertainty: null },
      { text: "Must follow MLH Code of Conduct", type: "other", mandatory: "mandatory", excerpt: "MLH Code of Conduct applies", source_ref: "rules", comparison_rule: null, uncertainty: null },
    ],
    application_questions: [
      "What's the coolest project you've built?",
      "Why do you want to attend HackMIT?",
    ],
    required_documents: [],
    application_steps: [
      "Register on HackMIT website",
      "Form a team (or join solo)",
      "Attend opening ceremony",
      "Hack for 24 hours",
      "Present and demo",
    ],
    source_url: "https://hackmit.org/",
    source_content: "HackMIT is one of the premier hackathons in the US. 24-hour hackathon at MIT campus with hybrid participation option.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000004",
    created_by: "system",
    title: "Thiel Fellowship 2026",
    organizer: "Thiel Foundation",
    category: "fellowship",
    summary:
      "A $100,000 fellowship for young people (under 23) who want to build new things instead of sitting in a classroom. Two-year fellowship with mentorship, network, and capital.",
    location: "Flexible / Global",
    participation_mode: "remote",
    deadline: "2026-11-30T23:59:59Z",
    deadline_timezone: "UTC",
    deadline_timezone_known: true,
    deadline_raw_text: "November 30, 2026",
    funding_kind: "stipend",
    funding_description: "$100,000 paid in stages over two years. Additional mentorship and network access.",
    funding_amount_min: 100000,
    funding_amount_max: 100000,
    funding_currency: "USD",
    funding_conditional: false,
    requirements: [
      { text: "Must be 22 years old or younger", type: "age", mandatory: "mandatory", excerpt: "Under 23 years old", source_ref: "eligibility", comparison_rule: { field: "age", operator: "lte", value: 22 }, uncertainty: null },
      { text: "Must have a venture or project in development", type: "experience", mandatory: "mandatory", excerpt: "Must have a specific venture or project you are working on", source_ref: "eligibility", comparison_rule: null, uncertainty: "Subjective evaluation" },
      { text: "Must be willing to drop out or take leave from formal education", type: "other", mandatory: "mandatory", excerpt: "Must be willing to step away from traditional education", source_ref: "commitment", comparison_rule: null, uncertainty: "Fellowship encourages but does not require dropping out" },
    ],
    application_questions: [
      "What are you building and why does it matter?",
      "What makes you the right person to build this?",
      "What is your unfair advantage?",
    ],
    required_documents: ["Project pitch/deck (optional)"],
    application_steps: [
      "Submit application online",
      "First round review",
      "Interviews with Thiel team",
      "Final decision",
    ],
    source_url: "https://thielfellowship.org/",
    source_content: "The Thiel Fellowship gives $100,000 to young people who want to build new things. Fellows receive mentorship, a network, and funding.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000005",
    created_by: "system",
    title: "Girls Who Impact Grant 2026",
    organizer: "Girls Who Code",
    category: "grant",
    summary:
      "Grants of up to $5,000 for women and non-binary students pursuing computer science projects, startups, or community initiatives.",
    location: "Remote",
    participation_mode: "remote",
    deadline: "2026-08-15T23:59:59Z",
    deadline_timezone: "UTC",
    deadline_timezone_known: true,
    deadline_raw_text: "August 15, 2026",
    funding_kind: "stipend",
    funding_description: "Up to $5,000 grant. No strings attached.",
    funding_amount_min: 1000,
    funding_amount_max: 5000,
    funding_currency: "USD",
    funding_conditional: false,
    requirements: [
      { text: "Must identify as woman or non-binary", type: "nationality", mandatory: "mandatory", excerpt: "For women and non-binary individuals", source_ref: "eligibility", comparison_rule: null, uncertainty: "Self-identification based" },
      { text: "Must be a student (any level)", type: "education_stage", mandatory: "mandatory", excerpt: "Must be currently enrolled as a student", source_ref: "eligibility", comparison_rule: { field: "education_stage", operator: "in_list", value: ["undergraduate", "masters", "phd"] }, uncertainty: null },
      { text: "Must be pursuing a CS-related project or initiative", type: "field_of_study", mandatory: "mandatory", excerpt: "Computer science related project", source_ref: "eligibility", comparison_rule: { field: "field_of_study", operator: "includes", value: "computer" }, uncertainty: null },
    ],
    application_questions: [
      "Describe your project or initiative",
      "How will the grant funds be used?",
      "What impact do you hope to achieve?",
    ],
    required_documents: ["Project proposal", "CV/Resume"],
    application_steps: [
      "Submit application online",
      "Review by selection committee",
      "Notify winners",
      "Disburse funds",
    ],
    source_url: "https://girlswhocode.com/grants",
    source_content: "Girls Who Impact Grants provide funding to women and non-binary students working on CS projects.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000006",
    created_by: "system",
    title: "Machine Learning Group Research Placement 2026",
    organizer: "University of Oxford",
    category: "fellowship",
    summary:
      "Paid 6-month research placement at the Oxford Machine Learning Group. Work on cutting-edge ML research with world-leading academics.",
    location: "Oxford, UK",
    participation_mode: "in-person",
    deadline: "2026-12-15T23:59:59Z",
    deadline_timezone: "Europe/London",
    deadline_timezone_known: true,
    deadline_raw_text: "December 15, 2026",
    funding_kind: "stipend",
    funding_description: "Monthly stipend of approximately £1,800. Travel and accommodation support.",
    funding_amount_min: 10800,
    funding_amount_max: 10800,
    funding_currency: "GBP",
    funding_conditional: false,
    requirements: [
      { text: "Must be enrolled in an undergraduate or graduate program", type: "education_stage", mandatory: "mandatory", excerpt: "Undergraduate and graduate students welcome", source_ref: "eligibility", comparison_rule: { field: "education_stage", operator: "in_list", value: ["undergraduate", "masters", "phd"] }, uncertainty: null },
      { text: "Strong background in machine learning", type: "skill", mandatory: "mandatory", excerpt: "Strong ML background", source_ref: "requirements", comparison_rule: { field: "skill", operator: "includes", value: "machine learning" }, uncertainty: null },
      { text: "Experience with Python and ML frameworks", type: "skill", mandatory: "mandatory", excerpt: "Python and ML frameworks", source_ref: "requirements", comparison_rule: { field: "skill", operator: "in_list", value: ["python", "pytorch", "tensorflow"] }, uncertainty: null },
    ],
    application_questions: [
      "Describe your ML research experience",
      "Which ML topics interest you most?",
      "What publications do you have (if any)?",
    ],
    required_documents: ["CV/Resume", "Research statement", "Two reference letters"],
    application_steps: [
      "Email professor with expression of interest",
      "Submit formal application",
      "Interview with research group",
      "Decision",
    ],
    source_url: null,
    source_content: "Oxford ML Group research placement. 6-month paid position working on cutting-edge ML research.",
    source_label: "user_provided",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000007",
    created_by: "system",
    title: "Caltech SURF (Summer Undergraduate Research) 2026",
    organizer: "California Institute of Technology",
    category: "fellowship",
    summary: "10-week summer research with Caltech faculty and NASA JPL scientists. Fully funded with $7,740 stipend.",
    location: "Pasadena, CA, USA",
    participation_mode: "in-person",
    deadline: "2026-06-01T23:59:59Z",
    deadline_timezone: "America/Los_Angeles",
    deadline_timezone_known: true,
    deadline_raw_text: "June 1, 2026",
    funding_kind: "stipend",
    funding_description: "$7,740 stipend for 10-week research period.",
    funding_amount_min: 7740,
    funding_amount_max: 7740,
    funding_currency: "USD",
    funding_conditional: false,
    requirements: [
      { text: "Must be enrolled undergraduate student", type: "education_stage", mandatory: "mandatory", excerpt: "Eligible undergraduates", source_ref: "eligibility", comparison_rule: { field: "education_stage", operator: "equals", value: "undergraduate" }, uncertainty: null },
      { text: "Cumulative GPA of 3.2 or higher", type: "academic", mandatory: "mandatory", excerpt: "Minimum 3.2 GPA", source_ref: "eligibility", comparison_rule: null, uncertainty: null }
    ],
    application_questions: ["Research project proposal", "Faculty mentor endorsement"],
    required_documents: ["CV/Resume", "Transcript", "2 Faculty recommendations"],
    application_steps: ["Identify Caltech mentor", "Draft research proposal", "Submit online application"],
    source_url: "https://sfp.caltech.edu/undergraduate-research/programs/surf",
    source_content: "Caltech Summer Undergraduate Research Fellowship program.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000008",
    created_by: "system",
    title: "CERN Summer Student Programme 2026",
    organizer: "CERN",
    category: "internship",
    summary: "8 to 13 weeks at CERN Geneva for physics, computing, and engineering students with generous living allowance.",
    location: "Geneva, Switzerland",
    participation_mode: "in-person",
    deadline: "2026-05-31T23:59:59Z",
    deadline_timezone: "Europe/Zurich",
    deadline_timezone_known: true,
    deadline_raw_text: "May 31, 2026",
    funding_kind: "stipend",
    funding_description: "92 CHF/day net subsistence allowance plus travel reimbursement.",
    funding_amount_min: 6500,
    funding_amount_max: 8500,
    funding_currency: "CHF",
    funding_conditional: false,
    requirements: [
      { text: "Completed at least 3 years of full-time university studies", type: "education_stage", mandatory: "mandatory", excerpt: "3 years of university completed", source_ref: "eligibility", comparison_rule: null, uncertainty: null },
      { text: "Good knowledge of English or French", type: "skill", mandatory: "mandatory", excerpt: "Working language proficiency", source_ref: "eligibility", comparison_rule: null, uncertainty: null }
    ],
    application_questions: ["Motivation letter", "Area of technical interest"],
    required_documents: ["CV/Resume", "Academic transcripts", "Two letters of recommendation"],
    application_steps: ["Submit SmartRecruiters application", "Upload references", "Committee review"],
    source_url: "https://careers.cern/summer",
    source_content: "CERN Summer Student Programme for physics and computing undergrads.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000009",
    created_by: "system",
    title: "Y Combinator Summer 2026 Batch",
    organizer: "Y Combinator",
    category: "fellowship",
    summary: "Standard $500,000 investment and 3-month intensive acceleration in San Francisco for early-stage builders.",
    location: "San Francisco, CA, USA",
    participation_mode: "in-person",
    deadline: "2026-04-15T23:59:59Z",
    deadline_timezone: "America/Los_Angeles",
    deadline_timezone_known: true,
    deadline_raw_text: "April 15, 2026",
    funding_kind: "stipend",
    funding_description: "$500k investment on standard post-money SAFE.",
    funding_amount_min: 500000,
    funding_amount_max: 500000,
    funding_currency: "USD",
    funding_conditional: true,
    requirements: [
      { text: "At least one technical founder who built the prototype", type: "skill", mandatory: "mandatory", excerpt: "Technical ability to build the product", source_ref: "eligibility", comparison_rule: null, uncertainty: null },
      { text: "Willing to spend 3 months in person in San Francisco", type: "location", mandatory: "mandatory", excerpt: "Must attend in person in SF", source_ref: "eligibility", comparison_rule: null, uncertainty: null }
    ],
    application_questions: ["What is your company going to make?", "Why did you choose this idea?", "Who is the team?"],
    required_documents: ["Founder video (1 min)", "Demo link / code"],
    application_steps: ["Complete online form", "Submit video", "10-minute partner interview"],
    source_url: "https://ycombinator.com/apply",
    source_content: "Y Combinator startup accelerator batch application.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000010",
    created_by: "system",
    title: "Emergent Ventures Moonshot Grant 2026",
    organizer: "Mercatus Center at George Mason University",
    category: "grant",
    summary: "Fast, unbureaucratic grants ($5,000 to $100,000) for highly ambitious young builders and thinkers.",
    location: "Remote / Global",
    participation_mode: "remote",
    deadline: "2026-12-31T23:59:59Z",
    deadline_timezone: "UTC",
    deadline_timezone_known: true,
    deadline_raw_text: "Rolling through 2026",
    funding_kind: "prize",
    funding_description: "Direct non-dilutive grant from $5,000 to $100,000.",
    funding_amount_min: 5000,
    funding_amount_max: 100000,
    funding_currency: "USD",
    funding_conditional: false,
    requirements: [
      { text: "High-upside scalable idea or personal trajectory", type: "experience", mandatory: "mandatory", excerpt: "Ambition and talent", source_ref: "eligibility", comparison_rule: null, uncertainty: null }
    ],
    application_questions: ["What is your moonshot idea?", "What makes you unusually capable of executing this?"],
    required_documents: ["Short proposal (max 1500 words)"],
    application_steps: ["Submit Google Form", "Tyler Cowen review", "Direct interview if shortlisted"],
    source_url: "https://www.mercatus.org/emergent-ventures",
    source_content: "Emergent Ventures grant program directed by Tyler Cowen.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000011",
    created_by: "system",
    title: "Neo Scholars & Fellows 2026",
    organizer: "Neo",
    category: "fellowship",
    summary: "Elite community of undergraduate CS builders with guaranteed summer startup offers and annual retreat in Oregon.",
    location: "San Francisco / Remote",
    participation_mode: "hybrid",
    deadline: "2026-12-01T23:59:59Z",
    deadline_timezone: "America/Los_Angeles",
    deadline_timezone_known: true,
    deadline_raw_text: "December 1, 2026",
    funding_kind: "stipend",
    funding_description: "Guaranteed paid internship offer + funded annual retreat.",
    funding_amount_min: 15000,
    funding_amount_max: 30000,
    funding_currency: "USD",
    funding_conditional: false,
    requirements: [
      { text: "Undergraduate student graduating in 2026-2028", type: "education_stage", mandatory: "mandatory", excerpt: "Enrolled student", source_ref: "eligibility", comparison_rule: null, uncertainty: null },
      { text: "Strong coding ability demonstrated through GitHub or competitive programming", type: "skill", mandatory: "mandatory", excerpt: "Exceptional coding", source_ref: "requirements", comparison_rule: null, uncertainty: null }
    ],
    application_questions: ["Link your proudest technical build", "Coding assessment link"],
    required_documents: ["CV/Resume", "GitHub handle"],
    application_steps: ["Coding challenge", "Technical interview", "Final finalist interview"],
    source_url: "https://neo.com/scholars",
    source_content: "Neo Scholars mentorship and fellowship program.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000012",
    created_by: "system",
    title: "Cal Hacks 12.0",
    organizer: "UC Berkeley Cal Hacks",
    category: "hackathon",
    summary: "World's largest collegiate hackathon in San Francisco with $150k+ in prizes and full travel reimbursements.",
    location: "San Francisco, CA, USA",
    participation_mode: "in-person",
    deadline: "2026-10-10T23:59:59Z",
    deadline_timezone: "America/Los_Angeles",
    deadline_timezone_known: true,
    deadline_raw_text: "October 10, 2026",
    funding_kind: "prize",
    funding_description: "Over $150,000 in prizes plus travel stipend grants.",
    funding_amount_min: 1000,
    funding_amount_max: 20000,
    funding_currency: "USD",
    funding_conditional: true,
    requirements: [
      { text: "Must be a current undergraduate or graduate student", type: "education_stage", mandatory: "mandatory", excerpt: "Current student ID required", source_ref: "eligibility", comparison_rule: null, uncertainty: null }
    ],
    application_questions: ["Why do you want to attend Cal Hacks?", "What project do you envision building?"],
    required_documents: ["Student ID verification", "Resume"],
    application_steps: ["Online registration", "Lottery / selection", "RSVP confirm"],
    source_url: "https://calhacks.io",
    source_content: "Cal Hacks collegiate hackathon.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000013",
    created_by: "system",
    title: "ETHGlobal Virtual & European Hackathons 2026",
    organizer: "ETHGlobal",
    category: "hackathon",
    summary: "Premier developer hackathons for decentralized apps, smart contracts, and cryptographic protocols with $500k in prizes.",
    location: "Remote / Hybrid",
    participation_mode: "hybrid",
    deadline: "2026-07-20T23:59:59Z",
    deadline_timezone: "UTC",
    deadline_timezone_known: true,
    deadline_raw_text: "July 20, 2026",
    funding_kind: "prize",
    funding_description: "$500,000 pool in bounties, track prizes, and pool prizes.",
    funding_amount_min: 1000,
    funding_amount_max: 25000,
    funding_currency: "USD",
    funding_conditional: true,
    requirements: [
      { text: "Knowledge of Solidity, Rust, TypeScript, or Web3 tooling", type: "skill", mandatory: "preferred", excerpt: "Web3 experience", source_ref: "requirements", comparison_rule: null, uncertainty: null }
    ],
    application_questions: ["GitHub profile", "Smart contract project experience"],
    required_documents: ["GitHub handle"],
    application_steps: ["Apply on ETHGlobal dashboard", "Stake or verify", "Attend opening ceremony"],
    source_url: "https://ethglobal.com",
    source_content: "ETHGlobal developer hackathons.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000014",
    created_by: "system",
    title: "The Rhodes Scholarship (Oxford) 2027",
    organizer: "Rhodes Trust",
    category: "scholarship",
    summary: "Oldest and most prestigious international graduate scholarship, fully funding postgraduate study at the University of Oxford.",
    location: "Oxford, UK",
    participation_mode: "in-person",
    deadline: "2026-10-01T23:59:59Z",
    deadline_timezone: "UTC",
    deadline_timezone_known: true,
    deadline_raw_text: "October 1, 2026",
    funding_kind: "stipend",
    funding_description: "All university tuition fees covered plus annual living stipend of £19,092 and return flights.",
    funding_amount_min: 50000,
    funding_amount_max: 100000,
    funding_currency: "GBP",
    funding_conditional: false,
    requirements: [
      { text: "Citizen of an eligible Rhodes constituency", type: "nationality", mandatory: "mandatory", excerpt: "Constituency citizenship", source_ref: "eligibility", comparison_rule: null, uncertainty: null },
      { text: "First-class honors degree or equivalent high GPA", type: "academic", mandatory: "mandatory", excerpt: "Academic excellence", source_ref: "eligibility", comparison_rule: null, uncertainty: null }
    ],
    application_questions: ["Personal statement", "Proposed course of study at Oxford"],
    required_documents: ["CV/Resume", "Academic transcripts", "4 to 6 recommendation letters"],
    application_steps: ["Constituency preliminary selection", "National interview panel", "Oxford admission"],
    source_url: "https://www.rhodeshouse.ox.ac.uk",
    source_content: "The Rhodes Trust international scholarship.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000015",
    created_by: "system",
    title: "Linux Foundation LFX Mentorship Summer 2026",
    organizer: "The Linux Foundation",
    category: "internship",
    summary: "Paid remote mentorship working on critical open-source infrastructure (Kubernetes, Envoy, Linux Kernel, OpenSSF).",
    location: "Remote",
    participation_mode: "remote",
    deadline: "2026-05-15T23:59:59Z",
    deadline_timezone: "UTC",
    deadline_timezone_known: true,
    deadline_raw_text: "May 15, 2026",
    funding_kind: "stipend",
    funding_description: "Stipend between $3,000 and $6,600 depending on country of residence.",
    funding_amount_min: 3000,
    funding_amount_max: 6600,
    funding_currency: "USD",
    funding_conditional: false,
    requirements: [
      { text: "Proficiency in Go, C, C++, Rust, or Python", type: "skill", mandatory: "mandatory", excerpt: "Language proficiency", source_ref: "requirements", comparison_rule: null, uncertainty: null },
      { text: "Able to commit 20-40 hours per week for 12 weeks", type: "time", mandatory: "mandatory", excerpt: "Time availability", source_ref: "timeline", comparison_rule: null, uncertainty: null }
    ],
    application_questions: ["Why are you interested in this project?", "Previous open-source contributions"],
    required_documents: ["Resume", "Proof of enrollment or eligibility"],
    application_steps: ["Browse projects on LFX portal", "Submit proposal to mentor", "Mentor selection"],
    source_url: "https://lfx.linuxfoundation.org/tools/mentorship",
    source_content: "LFX Mentorship program by Linux Foundation.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000016",
    created_by: "system",
    title: "Schwarzman Scholars Cohort 2027",
    organizer: "Tsinghua University & Schwarzman College",
    category: "scholarship",
    summary: "Fully funded 1-year master's program in Global Affairs at Tsinghua University in Beijing with world-class faculty.",
    location: "Beijing, China",
    participation_mode: "in-person",
    deadline: "2026-09-15T23:59:59Z",
    deadline_timezone: "America/New_York",
    deadline_timezone_known: true,
    deadline_raw_text: "September 15, 2026",
    funding_kind: "stipend",
    funding_description: "Full tuition, room and board, travel allowance, and $4,000 personal stipend.",
    funding_amount_min: 40000,
    funding_amount_max: 60000,
    funding_currency: "USD",
    funding_conditional: false,
    requirements: [
      { text: "Undergraduate degree completed before matriculation", type: "education_stage", mandatory: "mandatory", excerpt: "Completed bachelor degree", source_ref: "eligibility", comparison_rule: null, uncertainty: null },
      { text: "Age between 18 and 28 years old", type: "age", mandatory: "mandatory", excerpt: "Must not have reached 29th birthday", source_ref: "eligibility", comparison_rule: { field: "age", operator: "lte", value: 28 }, uncertainty: null }
    ],
    application_questions: ["Leadership essay", "Statement of purpose", "Current affairs essay"],
    required_documents: ["Transcripts", "3 Recommendation letters", "Video introduction"],
    application_steps: ["Submit online application", "Semifinal interviews", "Global selection"],
    source_url: "https://www.schwarzmanscholars.org",
    source_content: "Schwarzman Scholars fellowship in Beijing.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000017",
    created_by: "system",
    title: "Generation Google Scholarship (EMEA) 2026",
    organizer: "Google",
    category: "scholarship",
    summary: "€7,000 award for students pursuing computer science degrees who excel academically and demonstrate leadership.",
    location: "Remote",
    participation_mode: "remote",
    deadline: "2026-06-15T23:59:59Z",
    deadline_timezone: "UTC",
    deadline_timezone_known: true,
    deadline_raw_text: "June 15, 2026",
    funding_kind: "prize",
    funding_description: "€7,000 merit-based academic scholarship.",
    funding_amount_min: 7000,
    funding_amount_max: 7000,
    funding_currency: "EUR",
    funding_conditional: false,
    requirements: [
      { text: "Enrolled as a full-time student in a university in Europe, Middle East, or Africa", type: "residency", mandatory: "mandatory", excerpt: "Enrolled in EMEA institution", source_ref: "eligibility", comparison_rule: null, uncertainty: null },
      { text: "Studying Computer Science, Computer Engineering, or closely related technical field", type: "field", mandatory: "mandatory", excerpt: "Technical field of study", source_ref: "eligibility", comparison_rule: null, uncertainty: null }
    ],
    application_questions: ["Describe a time when you solved a complex technical problem", "How do you champion diversity in tech?"],
    required_documents: ["Resume", "Academic transcripts", "Letter of reference"],
    application_steps: ["Submit Google application", "Coding challenge (if requested)", "Award notification"],
    source_url: "https://buildyourfuture.withgoogle.com/scholarships",
    source_content: "Generation Google Scholarship program.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 11 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1000000-0000-4000-8000-000000000018",
    created_by: "system",
    title: "Outreachy Diversity Internship Summer 2026",
    organizer: "Outreachy / Software Freedom Conservancy",
    category: "internship",
    summary: "$7,000 paid remote internship supporting underrepresented contributors in open source and open science.",
    location: "Remote",
    participation_mode: "remote",
    deadline: "2026-04-10T23:59:59Z",
    deadline_timezone: "UTC",
    deadline_timezone_known: true,
    deadline_raw_text: "April 10, 2026",
    funding_kind: "stipend",
    funding_description: "$7,000 USD stipend plus $500 travel grant.",
    funding_amount_min: 7000,
    funding_amount_max: 7500,
    funding_currency: "USD",
    funding_conditional: false,
    requirements: [
      { text: "Subject to systemic bias or underrepresented in tech industry", type: "diversity", mandatory: "mandatory", excerpt: "Underrepresented demographics", source_ref: "eligibility", comparison_rule: null, uncertainty: null },
      { text: "Available for 40 hours per week during 3-month internship", type: "time", mandatory: "mandatory", excerpt: "Full-time commitment", source_ref: "timeline", comparison_rule: null, uncertainty: null }
    ],
    application_questions: ["Initial eligibility essay", "Contribution period records"],
    required_documents: ["Contribution PR links on participating projects"],
    application_steps: ["Initial application", "Make recorded contributions to project", "Final selection by mentor"],
    source_url: "https://www.outreachy.org",
    source_content: "Outreachy remote diversity internships.",
    source_label: "fetched",
    source_status: "live",
    extracted_at: new Date().toISOString(),
    status: "published",
    is_demo: false,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

